#Evento em que será disparado o workflow
on: push


jobs:
  #Nome da configuracao do sistema operacional
  job1-hello:
    runs-on: ubuntu-latest
    #instrucao para executar dentro do sistema operacional
    steps:
      - name: Imprimir mensagem
        run: echo "Olá, Mundo"

  #Nome da configuracao do sistema operacional
  job2-goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Sequencia de instruções
        run: |
          echo "Uma nova instrução"
          ls
      - name: Step 2 - Imprimir mensagem
        run: echo "Até logo!"